/**
 * Default configurations and knowledge bases for the Identity Scorer.
 */

/**
 * Top globally impersonated brands across Tech, Cloud, Banking, Logistics, and Consumer services.
 */
export const DEFAULT_PROTECTED_DOMAINS: string[] = [
  // Tech & Cloud
  'microsoft.com',
  'google.com',
  'apple.com',
  'amazon.com',
  'meta.com',
  'facebook.com',
  'linkedin.com',
  'dropbox.com',
  'adobe.com',
  'github.com',
  'salesforce.com',
  'zoom.us',
  'slack.com',
  'cloudflare.com',
  'docusign.com',
  'oracle.com',
  'cisco.com',
  'atlassian.com',

  // Financial & Banking & Payment
  'paypal.com',
  'stripe.com',
  'square.com',
  'squareup.com',
  'chase.com',
  'bankofamerica.com',
  'wellsfargo.com',
  'citigroup.com',
  'citi.com',
  'americanexpress.com',
  'visa.com',
  'mastercard.com',
  'capitalone.com',
  'fidelity.com',
  'schwab.com',
  'vanguard.com',
  'robinhood.com',
  'coinbase.com',
  'binance.com',

  // Logistics & Shipping
  'dhl.com',
  'ups.com',
  'fedex.com',
  'usps.com',

  // Streaming & Consumer
  'netflix.com',
  'spotify.com',
  'target-corp.com',
  'target.com',
  'walmart.com',
  'ebay.com',
  'bestbuy.com',
  'costco.com',
  'booking.com',
  'airbnb.com',
  'uber.com',
];

/**
 * Curated mapping of multi-brand/product aliases for display-name impersonation detection.
 */
export const DEFAULT_BRAND_ALIASES: Record<string, string[]> = {
  'microsoft.com': [
    'microsoft',
    'microsoft 365',
    'office 365',
    'o365',
    'outlook',
    'azure',
    'onedrive',
    'microsoft security',
    'microsoft account',
    'microsoft billing',
    'msft',
  ],
  'google.com': [
    'google',
    'gmail',
    'google workspace',
    'google cloud',
    'google drive',
    'google security',
    'google account',
  ],
  'apple.com': [
    'apple',
    'icloud',
    'apple id',
    'apple support',
    'apple care',
    'app store',
    'apple security',
  ],
  'amazon.com': [
    'amazon',
    'aws',
    'amazon web services',
    'amazon prime',
    'amazon pay',
    'amazon security',
    'amazon support',
  ],
  'paypal.com': [
    'paypal',
    'paypal security',
    'paypal service',
    'paypal support',
    'paypal billing',
    'paypal notice',
  ],
  'docusign.com': [
    'docusign',
    'docusign envelope',
    'docusign document',
    'docusign sign',
    'docusign support',
  ],
  'netflix.com': [
    'netflix',
    'netflix support',
    'netflix billing',
    'netflix membership',
  ],
  'adobe.com': [
    'adobe',
    'adobe creative cloud',
    'adobe document cloud',
    'acrobat',
    'adobe sign',
  ],
  'chase.com': [
    'chase',
    'chase bank',
    'jpmorgan',
    'jp morgan',
    'chase online',
    'chase security',
  ],
  'bankofamerica.com': [
    'bank of america',
    'bofa',
    'bankofamerica',
    'merrill lynch',
  ],
  'wellsfargo.com': [
    'wells fargo',
    'wellsfargo',
    'wells fargo online',
  ],
  'stripe.com': [
    'stripe',
    'stripe payments',
    'stripe billing',
    'stripe invoices',
  ],
  'dhl.com': [
    'dhl',
    'dhl express',
    'dhl tracking',
    'dhl delivery',
    'dhl logistics',
  ],
  'ups.com': [
    'ups',
    'united parcel service',
    'ups tracking',
    'ups delivery',
    'ups shipping',
  ],
  'fedex.com': [
    'fedex',
    'federal express',
    'fedex tracking',
    'fedex delivery',
    'fedex ground',
  ],
  'linkedin.com': [
    'linkedin',
    'linkedin security',
    'linkedin messaging',
  ],
  'meta.com': [
    'facebook',
    'meta',
    'instagram',
    'whatsapp',
    'meta security',
    'facebook security',
  ],
  'facebook.com': [
    'facebook',
    'meta',
    'instagram',
    'whatsapp',
    'facebook security',
  ],
  'dropbox.com': [
    'dropbox',
    'dropbox sign',
    'dropbox notification',
  ],
  'coinbase.com': [
    'coinbase',
    'coinbase security',
    'coinbase support',
    'coinbase wallet',
  ],
  'target-corp.com': [
    'target',
    'target corp',
    'target security',
  ],
  'target.com': [
    'target',
    'target store',
    'target circle',
  ],
};

/**
 * Action-oriented high-risk phishing keywords used in combosquatting patterns.
 */
export const HIGH_RISK_KEYWORDS: string[] = [
  'login',
  'signin',
  'sign-in',
  'log-in',
  'secure',
  'security',
  'verify',
  'verification',
  'auth',
  'authenticate',
  'authentication',
  'password',
  'passcode',
  'account',
  'update',
  'portal',
  'recovery',
  'confirm',
  'validation',
  'billing',
  'invoice',
  'support',
  'helpdesk',
  'service',
  'alert',
  'notice',
  'wallet',
  'banking',
  'statement',
  'document',
  'sign',
  'envelope',
];

/**
 * Known high-abuse/phishing Top-Level Domains (TLDs).
 */
export const HIGH_RISK_TLDS: Set<string> = new Set([
  'xyz',
  'top',
  'tk',
  'work',
  'click',
  'buzz',
  'cfd',
  'rest',
  'online',
  'site',
  'vip',
  'live',
  'loan',
  'app',
  'cc',
  'support',
  'security',
  'icu',
  'monster',
  'cyou',
  'gq',
  'ml',
  'cf',
  'ga',
  'sbs',
  'quest',
]);

/**
 * Common consumer and free webmail domains.
 * Used exclusively to suppress the generic personal display-name mismatch heuristic.
 */
export const FREE_WEBMAIL_DOMAINS: Set<string> = new Set([
  'gmail.com',
  'googlemail.com',
  'yahoo.com',
  'ymail.com',
  'outlook.com',
  'hotmail.com',
  'live.com',
  'msn.com',
  'icloud.com',
  'me.com',
  'mac.com',
  'aol.com',
  'mail.com',
  'zoho.com',
  'proton.me',
  'protonmail.com',
  'fastmail.com',
  'gmx.com',
  'gmx.net',
  'tutanota.com',
  'tutamail.com',
  'hey.com',
]);
